// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package http

import (
	http "github.com/go-kit/kit/transport/http"
	mux "github.com/gorilla/mux"
	endpoint "github.com/piusalfred/regsvc/pkg/endpoint"
	http1 "net/http"
)

// NewHTTPHandler returns a handler that makes a set of endpoints available on
// predefined paths.
func NewHTTPHandler(endpoints endpoint.Endpoints, options map[string][]http.ServerOption) http1.Handler {
	m := mux.NewRouter()
	makeRegisterHandler(m, endpoints, options["Register"])
	makeLoginHandler(m, endpoints, options["Login"])
	makeAddUserHandler(m, endpoints, options["AddUser"])
	makeGetUserByIdHandler(m, endpoints, options["GetUserById"])
	makeListUsersHandler(m, endpoints, options["ListUsers"])
	makeDeleteUserHandler(m, endpoints, options["DeleteUser"])
	makeUpdateUserHandler(m, endpoints, options["UpdateUser"])
	makeAddNodeHandler(m, endpoints, options["AddNode"])
	makeGetNodeByIdHandler(m, endpoints, options["GetNodeById"])
	makeListNodesHandler(m, endpoints, options["ListNodes"])
	makeDeleteNodeHandler(m, endpoints, options["DeleteNode"])
	makeUpdateNodeHandler(m, endpoints, options["UpdateNode"])
	makeAddRegionHandler(m, endpoints, options["AddRegion"])
	makeGetRegionByIdHandler(m, endpoints, options["GetRegionById"])
	makeListRegionsHandler(m, endpoints, options["ListRegions"])
	makeDeleteRegionHandler(m, endpoints, options["DeleteRegion"])
	makeUpdateRegionHandler(m, endpoints, options["UpdateRegion"])
	return m
}
